remote_theme: pages-themes/primer
title: hoge
description: foo
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://deanattali.com"
